CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE auth.tb_email_auth (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    email             VARCHAR(255) NOT NULL,
    auth_code         VARCHAR(100) NOT NULL,
    expires_at        TIMESTAMP NOT NULL,
    verified_at       TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth.tb_login_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    ip_address        VARCHAR(45),
    user_agent        VARCHAR(500),
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- DROP TABLE auth.tb_email_auth;
-- DROP TABLE auth.tb_login_history;
