-- citext 사용 시 필요
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE tb_email_auth (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        UUID NOT NULL UNIQUE,
    email             CITEXT NOT NULL,
    purpose           VARCHAR(30) NOT NULL,
    email_verified    BOOLEAN NOT NULL DEFAULT false,
    verified_at       TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

drop table tb_email_auth;