CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE auth.tb_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               CITEXT NOT NULL UNIQUE,
    password_hash       VARCHAR(255),
    nickname            VARCHAR(50) UNIQUE NOT NULL,
    profile_image_url   TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    email_verified      BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at       TIMESTAMP,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- DROP TABLE auth.tb_user;
