-- citext 사용 시 필요
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE tb_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID NOT NULL UNIQUE,
    email           CITEXT NOT NULL UNIQUE,
    nickname        VARCHAR(50),
    picture_url     TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ
);

drop table tb_users;